import type { Metadata } from "next";
import { Inter,Sarabun } from "next/font/google";

import "./globals.css";

const sarabun = Sarabun({
  subsets: ["latin", "thai"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "MUI table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={sarabun.className}>
          <main>{children}</main>
        </body>
    </html>
  );
}
